#!/usr/bin/env bash

# Install now
npm i -g now

# Delete the old deployment
now \
  -t "$TOKEN" \
  rm -y $DOMAINNAME

# Deploy changes to a fresh URL
now -C \
  -t "$TOKEN" \
  -n "$DOMAINNAME" \
   ./build

# Grab deploy URL
deploy_url=$(
 now -t $TOKEN ls $DOMAINNAME |
 awk '/ url/,EOF' |
 tail -n +2 |
 awk '{ print $1 }'
)

now \
  -t "$TOKEN" \
   alias set "$deploy_url" $DOMAINNAME
